project:
  type: website
  output-dir: docs

website:
  title: "Proyecto Visualización de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: Proyecto.qmd
        text: Proyecto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

