project:
  type: website
  output-dir: docs

website:
  title: "Proyecto de Visualización de Datos: Terremotos"
  
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: Limpieza.qmd
        text: Limpieza
      - href: Proyecto.qmd
        text: Análisis
      - href: about.qmd
        text: Acerca de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true