# Importación
## Empezamos con la importación desde Kaggle
```{python}
import kagglehub

path = kagglehub.dataset_download(
    "dhrubangtalukdar/200-years-of-global-major-earthquakes-18262026"
)

print("Path to dataset files:", path)
```

## Importamos las librerías necesarias para limpieza
```{python}
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

data = pd.read_csv(f"{path}/earthquake1826_2026.csv")
```


# Lectura de los datos:
```{python}
data
```


## Transformamos los tipos de datos
```{python}
data['tiempo'] = pd.to_datetime(data['time'], format = 'ISO8601')
```


## Se crean dos columnas para mayor comodidad al trabajar con fechas
```{python}
data['fecha'] = data['tiempo'].dt.date
data['hora'] = data['tiempo'].dt.time
```


## Información de los datos
```{python}
data.info()
```

# Descripción de los datos
### Se puede observar que existen aproximadamente cien mil observaciones. Existen datos nulos en algunas variables debido a las limitaciones de las herramientas de medición en países en desarrollo y en general las mediciones que se realizaron hace mucho tiempo. Es necesario realizar una selección de las variables que nos iteresan, luego una limpieza y transformación de formatos para facilitar la lectura y procesamiento  de los datos.

# Limpieza y transformación de datos
```{python}
data['tiempo'] = pd.to_datetime(data['time'], format = 'ISO8601')
data['fecha'] = data['tiempo'].dt.date
data['hora'] = data['tiempo'].dt.time

columnas_correctas = ['fecha', 'hora', 'latitude', 'longitude', 'depth', 'mag']
data_final = data[columnas_correctas]
data_final
```

## Datos duplicados
```{python}
data.duplicated().sum()
```
## Número de valores nulos debido a que son datos muy antiguos:
```{python}
data_final['depth'].isnull().sum()
```

### Hay 593 valores nulos de profundidad, estos valores se mantendrán debido a que la evolución temporal de los terremotos se realizará con las columnas de fecha, magnitud y coordenadas y es conveniente para el análisis conservar los registros más antiguos aunque no se tenga el dato de profundidad.